version: '3'

services:

  labo-indexation-ai-jupyterlab:
    #build: ./image/
    image: labo-image-test
    container_name: labo-indexation-ai-jupyterlab
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    ports:
      - ${LABO_INDEXATION_AI_HTTP_PORT}:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: ${LABO_INDEXATION_AI_JUPYTER_TOKEN}
      LABO_INDEXATION_AI_GIT_REPO1_URL: ${LABO_INDEXATION_AI_GIT_REPO1_URL}
      LABO_INDEXATION_AI_GIT_REPO1_NAME: ${LABO_INDEXATION_AI_GIT_REPO1_NAME}
      LABO_INDEXATION_AI_GIT_REPO2_URL: ${LABO_INDEXATION_AI_GIT_REPO2_URL}
      LABO_INDEXATION_AI_GIT_REPO2_NAME: ${LABO_INDEXATION_AI_GIT_REPO2_NAME}
    # https://jupyter-notebook.readthedocs.io/en/stable/config.html
